### PR TITLE
add option to avoid clearing terminal

### PR DESCRIPTION
**Pull request by moimikey**
i kinda don't like it, so let's add an option to disable it?

### CODE REVIEW

**Comment by lukeed** [comment]
Hey, thanks! Would you be okay with a "soft" clear instead of none at all?

Pass `clear(true)` to test it out then lemme know!

**Comment by moimikey** [comment]
i had dropped the ball on this :) will give it a try. thanks for the tip.

**Comment by ostrgard** [comment]
Any chance we could get this rolling? Soft clear would not help much in our case as we're running a few services simultaneously in docker and don't want output from a specific service to clear everything else while developing. 

That being said, soft clear would be a nice option, maybe even a better default :)

**Comment by lukeed** [comment]
Hey guys, sorry about the delay on this – totally forgot about it!

I just changed it so that it's _always_ a soft clear. That's what I found to be most acceptable across all other tools too, so I just kept it consistent. There's never really a reason you want to flat-out destroy history, so "soft" is the way to go.

Thanks!

**Pull request closed without merging**
