### PR TITLE
fix(webpack): new plugin API

### PR DESCRIPTION
**Pull request by mkleywegt**
This pull request updates the plugin hooks for Webpack 4's new plugin API

### CODE REVIEW

**Comment by lukeed** [comment]
Super cool, thanks! This makes it compatible ONLY with Webpack 4 right?

**Comment by mkleywegt** [comment]
Right. I guess this should go in a breaking change next version -- seeing as the Webpack team intends to phase out the old plugin API.

**Comment by lukeed** [comment]
Cool, thanks @mkleywegt~! This will be in a new major release 👍 I'm going to see if there are some other changes I'd like to include in that release.

**Comment by lukeed** [comment]
Hey @mkleywegt, this seems to be a good way to handle both versions. 

Do you mind running this locally for me, as a second set of eyes?

**Review by lukeed — APPROVED** [review]

**Pull request merged**
